task: detection

model: RTDETR
criterion: RTDETRCriterionv2
postprocessor: RTDETRPostProcessor


use_focal_loss: True
eval_spatial_size: [640, 640] # h w


RTDETR: 
  backbone: SwinBackbone
  encoder: HybridEncoder
  decoder: RTDETRTransformerv2
  

PResNet:
  depth: 50
  variant: d
  freeze_at: 0
  return_idx: [1, 2, 3]
  num_stages: 4
  freeze_norm: True
  pretrained: True 

RegionCLIPResNet:
  depth: 50
  return_idx: [1, 2, 3]
  freeze_at: 0
  input_resolution: 224
  pool_vec: False
  create_attnpool: False
  norm_type: frozenbn
  pretrained: True # set to checkpoint path to enable RegionCLIP weights
  pretrained_path: ./pretrained_ckpt/regionclip/regionclip_pretrained-cc_rn50.pth
  strict_load: False

SwinBackbone:
  model_name: swin_large_patch4_window12_384_in22k
  pretrained: True
  checkpoint_path: 
  img_size: 640
  drop_path_rate: 0.2
  out_indices: [1, 2, 3]
  out_channels: [512, 1024, 2048]


HybridEncoder:
  in_channels: [512, 1024, 2048]
  feat_strides: [8, 16, 32]

  # intra
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.
  enc_act: 'gelu'
  
  # cross
  expansion: 1.0
  depth_mult: 1
  act: 'silu'


RTDETRTransformerv2:
  feat_channels: [256, 256, 256]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  num_levels: 3

  num_layers: 6
  num_queries: 300

  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0 # 1.0 0.4

  eval_idx: -1

  # NEW
  num_points: [4, 4, 4] # [3,3,3] [2,2,2]
  cross_attn_method: default # default, discrete
  query_select_method: default # default, agnostic 


RTDETRPostProcessor:
  num_top_queries: 300


RTDETRCriterionv2:
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2, loss_reconstruction_l2: 1, loss_contrastive: 0.05}
  losses: ['vfl', 'boxes', 'reconstruction', ]
  alpha: 0.75
  gamma: 2.0

  matcher:
    type: HungarianMatcher
    weight_dict: {cost_class: 2, cost_bbox: 5, cost_giou: 2}
    alpha: 0.25
    gamma: 1.5

