__include__: [
  '../dataset/coco_detection_c2fc.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]

epoches: 72
output_dir: ./output/rtdetrv2_r50vd_6x_coco_c2fc

dinosaur_checkpoint: "importantpt/hsa.pt"
dinosaur_isa: False
dinosaur_lr: 1e-5


use_teacher: False
use_HSA: True

RTDETRTransformerv2:
  contrastive_loss: False
  HSA: True

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

