__include__: [
  '../dataset/coco_detection_self_training_c2bdd.yml',
  '../runtime.yml',
  # './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


output_dir: ./output/rtdetrv2_r50vd_6x_coco_self_training_c2bdd

dinosaur_checkpoint: "importantpt/hsa.pt"
dinosaur_isa: False
dinosaur_lr: 1e-5  # Set learning rate for DINOSAURpp component separately

epoches: 12
use_teacher: True
use_HSA: True
burn_epochs: 0
# pseudo_threshold: 0.4
ema_decay_teacher: 0.9993
nms_iou_threshold: 0.5
t_max: 0.55
t_min: 0.4
beta: 0.25
thresholdmethod: 'cos'
teacher_path: './output/importantpt/best_c2bdd.pth'

RTDETRTransformerv2:
  contrastive_loss: True
  HSA: True

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

