__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


output_dir: ./output/rtdetrv2_r101vd_6x_coco

dinosaur_checkpoint: "/home/qzh/daod/RT-DETRv2-15/importantpt/new_coco99.pt"
dinosaur_isa: False
dinosaur_lr: 1e-5  # Set learning rate for DINOSAURpp component separately

use_teacher: False
use_HSA: True

# RTDETRTransformerv2:
#   HSA: True

PResNet:
  depth: 101


HybridEncoder:
  # intra
  hidden_dim: 384
  dim_feedforward: 2048


RTDETRTransformerv2:
  feat_channels: [384, 384, 384]
  HSA: True


optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

